name: "Build"
on:
  push:

jobs:
  build:
    name: Build and Artifact
    # runs-on: ubuntu-20.04
    permissions:
      contents: write
    # Multi platfrom support
    strategy:
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]
      fail-fast: false

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Wait Tests
        id: test_result
        uses: Sibz/await-status-action@v1.0.1
        with:
          contexts: test-status
          authToken: ${{ secrets.GITHUB_TOKEN }}
          timeout: 30
      - name: Check Test Result
        if: steps.test_result.outputs.result != 'success'
        run: |
          echo "feiled ${{ steps.test_result.outputs.failedCheckNames }}"
          echo "status ${{ steps.test_result.outputs.failedCheckStates }}"
          exit 1
      - name: Checkout Sources
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Get arch on Windows
        id: gaw
        if: ${{ matrix.platform == 'windows-latest' }}
        run: echo "ARCH=x86_64" >> $GITHUB_ENV

      - name: Get arch on Other
        if: "!(steps.gaw.conclusion == 'success')"
        run: echo "ARCH=$(uname -m)" >> $GITHUB_ENV
        shell: bash

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install tauri dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install dependencies
        run: yarn install

      - name: Build MacOS
        id: bm
        if: ${{ matrix.platform == 'macos-latest' }}
        run: |
          rustup target add aarch64-apple-darwin
          yarn tauri build --target universal-apple-darwin

      - name: Build Other
        if: "!(steps.bm.conclusion == 'success')"
        run: yarn tauri build
        # ./build.sh

      - name: Artifact AppImage
        uses: actions/upload-artifact@v3
        with:
          name: Artifact-AppImage-${{ env.ARCH }}-${{ runner.os }}
          path: src-tauri/target/release/bundle/appimage/*.AppImage

      - name: Artifact Deb
        uses: actions/upload-artifact@v3
        with:
          name: Artifact-deb-${{ env.ARCH }}-${{ runner.os }}
          path: src-tauri/target/release/bundle/deb/*.deb
 
      - name: Artifact Mac App
        uses: actions/upload-artifact@v3
        with:
          name: Artifact-app-${{ runner.os }}
          path: src-tauri/target/release/bundle/macos/*.app

      - name: Artifact Dmg
        uses: actions/upload-artifact@v3
        with:
          name: Artifact-dmg-${{ runner.os }}
          path: src-tauri/target/release/bundle/dmg/*.dmg

      - name: Artifact Nsis
        uses: actions/upload-artifact@v3
        with:
          name: Artifact-nsis-${{ runner.os }}
          path: src-tauri/target/release/bundle/nsis/*.exe

      - name: Artifact Msi Installer
        uses: actions/upload-artifact@v3
        with:
          name: Artifact-msi-${{ runner.os }}
          path: src-tauri/target/release/bundle/msi/*.msi

